#DISCLAIMER: I dont take any responsability of how you're gonna use it
#its created only for fun, educational purposes, and --->certificated<--- penetration testing things
def encode(text):
    try:
        encoding_map = {
            "\x00": "LL",
            "\x01": "meow",
            "\x02": "kK",
            "\x03": "Kk",
            "\x04": "mM",
            "\x05": "Mm",
            "\x06": "sK",
            "\x07": "kS",
            "\x08": "MN",
            "\x09": "%M",
            "\x0A": "#",
            "\x0B": "£",
            "\x0C": "$",
            "\x0D": "!!!",
            "\x0E": "pQ",
            "\x0F": "<",
            "\x10": ">",
            "\x11": "(>.<)",
            "\x12": "(T.T)",
            "\x13": "(-.-)",
            "\x14": "(*^-^*)",
            "\x15": "^_^",
            "\x16": "=)",
            "\x17": "=(",
            "\x18": "(^o^)",
            "\x19": ":-)",
            "\x1A": ">:(",
            "\x1B": "<3",
            "\x1C": "(^-^)",
            "\x1D": ":3",
            "\x1E": ">:3",
            "\x1F": ">:-3",
            "\x20": ":-3",
            "\x21": "(-.-) .-=iii===-",
            "\x22": "kL",
            "\x23": "Maps-Maroon5",
            "\x24": "fhsdS",
            "\x25": "6t",
            "\x26": "fff",
            "\x27": "I",
            "\x28": "Wanna",
            "\x29": "die",
            "\x2A": "lol_jk",
            "\x2B": "m__-",
            "\x2C": "pqoO",
            "\x2D": "qWwWm",
            "\x2E": "iI._.",
            "\x2F": ".-.",
            "\x30": "._.",
            "\x31": ";-;",
            "\x32": "jJk",
            "\x33": "mLLnPo",
            "\x34": "sWa0",
            "\x35": "(UwU)",
            "\x36": "(OwO)",
            "\x37": ">:D",
            "\x38": ":-O",
            "\x39": "x_x",
            "\x3A": "zzz",
            "\x3B": "brb",
            "\x3C": "<==",
            "\x3D": "==>",
            "\x3E": "|||",
            "\x3F": "???",
            "\x40": "@_@",
            "\x41": "A_A",
            "\x42": "(b-b)",
            "\x43": "<o_o>",
            "\x44": "dD",
            "\x45": "o_o",
            "\x46": "(╯°□°）╯",
            "\x47": "UwU",
            "\x48": "T_T",
            "\x49": "(¬_¬)",
            "\x4A": "O_O",
            "\x4B": "(ಥ_ಥ)",
            "\x4C": "(☞ﾟヮﾟ)☞",
            "\x4D": "(ノಠ益ಠ)ノ",
            "\x4E": "YOLO",
            "\x4F": "XD",
            "\x50": ":P",
            "\x51": ":V",
            "\x52": "-_-",
            "\x53": ";_;",
            "\x54": "T^T",
            "\x55": "^o^",
            "\x56": "owo",
            "\x57": "(Q_Q)",
            "\x58": "(ಥ﹏ಥ)",
            "\x59": "(¬‿¬)",
            "\x5A": ">:|",
            "\x5B": "(≧ω≦)",
            "\x5C": "ʕ•ᴥ•ʔ",
            "\x5D": "(✿◕‿◕)",
            "\x5E": "(*≧ω≦)",
            "\x5F": "¯\\_(ツ)_/¯",
            "\x60": "(ノಥ益ಥ)ノ彡┻━┻",
            "\x61": "(✧ω✧)",
            "\x62": "QAQ",
            "\x63": "UwU",
            "\x64": "o_o",
            "\x65": "OwO",
            "\x66": "(っ◔◡◔)っ",
            "\x67": "(ง'̀-'́)ง",
            "\x68": "(๑•̀ㅂ•́)و",
            "\x69": "(￣ω￣)",
            "\x6A": "ヽ(°◇° )ノ",
            "\x6B": "(ノ´∀｀)ノ",
            "\x6C": "≧◡≦",
            "\x6D": "(´｡• ω •｡`)",
            "\x6E": "(>w<)",
            "\x6F": "ᕦ(ò_óˇ)ᕤ",
            "\x70": "(╬ಠ益ಠ)",
            "\x71": "(⊙_⊙)",
            "\x72": "(。_。)",
            "\x73": "(>_<)",
            "\x74": "(￣▽￣)ノ",
            "\x75": "ヽ(´ー` )┌",
            "\x76": "(•_•) ( •_•)>⌐■-■ (⌐■_■)",
            "\x77": "(ᵔᴥᵔ)",
            "\x78": "(≧◡≦)",
            "\x79": "(๑‾᷅⍨‾᷅๑)",
            "\x7A": "(✿´‿`)",
            "\x7B": "(⌒▽⌒)",
            "\x7C": "(✧ω✧)",
            "\x7D": "( ͡° ͜ʖ ͡°)",
            "\x7E": "＼(°o°)／",
            "\x7F": "(ಥ﹏ಥ)"
        }

        encoded_text = ""
        for char in text:
            encoded_text += encoding_map.get(char, char)  

        return encoded_text

    except Exception as e:
        print(f"An error occurred: {e}")
        return None

def decode(encoded_text):
    try:
        # Define a dictionary mapping each encoded string to its original character
        decoding_map = {
                "\x00": "LL",
                "\x01": "meow",
                "\x02": "kK",
                "\x03": "Kk",
                "\x04": "mM",
                "\x05": "Mm",
                "\x06": "sK",
                "\x07": "kS",
                "\x08": "MN",
                "\x09": "%M",
                "\x0A": "#",
                "\x0B": "£",
                "\x0C": "$",
                "\x0D": "!!!",
                "\x0E": "pQ",
                "\x0F": "<",
                "\x10": ">",
                "\x11": "(>.<)",
                "\x12": "(T.T)",
                "\x13": "(-.-)",
                "\x14": "(*^-^*)",
                "\x15": "^_^",
                "\x16": "=)",
                "\x17": "=(",
                "\x18": "(^o^)",
                "\x19": ":-)",
                "\x1A": ">:(",
                "\x1B": "<3",
                "\x1C": "(^-^)",
                "\x1D": ":3",
                "\x1E": ">:3",
                "\x1F": ">:-3",
                "\x20": ":-3",
                "\x21": "(-.-) .-=iii===-",
                "\x22": "kL",
                "\x23": "Maps-Maroon5",
                "\x24": "fhsdS",
                "\x25": "6t",
                "\x26": "fff",
                "\x27": "I",
                "\x28": "Wanna",
                "\x29": "die",
                "\x2A": "lol_jk",
                "\x2B": "m__-",
                "\x2C": "pqoO",
                "\x2D": "qWwWm",
                "\x2E": "iI._.",
                "\x2F": ".-.",
                "\x30": "._.",
                "\x31": ";-;",
                "\x32": "jJk",
                "\x33": "mLLnPo",
                "\x34": "sWa0",
                "\x35": "(UwU)",
                "\x36": "(OwO)",
                "\x37": ">:D",
                "\x38": ":-O",
                "\x39": "x_x",
                "\x3A": "zzz",
                "\x3B": "brb",
                "\x3C": "<==",
                "\x3D": "==>",
                "\x3E": "|||",
                "\x3F": "???",
                "\x40": "@_@",
                "\x41": "A_A",
                "\x42": "(b-b)",
                "\x43": "<o_o>",
                "\x44": "dD",
                "\x45": "o_o",
                "\x46": "(╯°□°）╯",
                "\x47": "UwU",
                "\x48": "T_T",
                "\x49": "(¬_¬)",
                "\x4A": "O_O",
                "\x4B": "(ಥ_ಥ)",
                "\x4C": "(☞ﾟヮﾟ)☞",
                "\x4D": "(ノಠ益ಠ)ノ",
                "\x4E": "YOLO",
                "\x4F": "XD",
                "\x50": ":P",
                "\x51": ":V",
                "\x52": "-_-",
                "\x53": ";_;",
                "\x54": "T^T",
                "\x55": "^o^",
                "\x56": "owo",
                "\x57": "(Q_Q)",
                "\x58": "(ಥ﹏ಥ)",
                "\x59": "(¬‿¬)",
                "\x5A": ">:|",
                "\x5B": "(≧ω≦)",
                "\x5C": "ʕ•ᴥ•ʔ",
                "\x5D": "(✿◕‿◕)",
                "\x5E": "(*≧ω≦)",
                "\x5F": "¯\\_(ツ)_/¯",
                "\x60": "(ノಥ益ಥ)ノ彡┻━┻",
                "\x61": "(✧ω✧)",
                "\x62": "QAQ",
                "\x63": "UwU",
                "\x64": "o_o",
                "\x65": "OwO",
                "\x66": "(っ◔◡◔)っ",
                "\x67": "(ง'̀-'́)ง",
                "\x68": "(๑•̀ㅂ•́)و",
                "\x69": "(￣ω￣)",
                "\x6A": "ヽ(°◇° )ノ",
                "\x6B": "(ノ´∀｀)ノ",
                "\x6C": "≧◡≦",
                "\x6D": "(´｡• ω •｡`)",
                "\x6E": "(>w<)",
                "\x6F": "ᕦ(ò_óˇ)ᕤ",
                "\x70": "(╬ಠ益ಠ)",
                "\x71": "(⊙_⊙)",
                "\x72": "(。_。)",
                "\x73": "(>_<)",
                "\x74": "(￣▽￣)ノ",
                "\x75": "ヽ(´ー` )┌",
                "\x76": "(•_•) ( •_•)>⌐■-■ (⌐■_■)",
                "\x77": "(ᵔᴥᵔ)",
                "\x78": "(≧◡≦)",
                "\x79": "(๑‾᷅⍨‾᷅๑)",
                "\x7A": "(✿´‿`)",
                "\x7B": "(⌒▽⌒)",
                "\x7C": "(✧ω✧)",
                "\x7D": "( ͡° ͜ʖ ͡°)",
                "\x7E": "＼(°o°)／",
                "\x7F": "(ಥ﹏ಥ)"

        }

        # Ensure longer encoded strings are checked first
        sorted_keys = sorted(decoding_map.keys(), key=len, reverse=True)
        
        # Start decoding the encoded text
        decoded_text = encoded_text

        for key in sorted_keys:
            decoded_text = decoded_text.replace(key, decoding_map[key])

        return decoded_text

    except Exception as e:
        print(f"An error occurred: {e}")
        return None

print("Encode: 1\nDecode: 2")
var = input("Select >>> ")
if(var == "1"):
    ivar = input("text >>> ")
    print(encode(ivar))
else:
    ivar1 = input("text >>> ")
    print(decode(ivar1))
